// <auto-generated />
using System;
using ExpenseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseTracker.Migrations
{
    [DbContext(typeof(ExpenseTrackerDbContext))]
    [Migration("20260808101937_SplitOriginAndSourceFormat")]
    partial class SplitOriginAndSourceFormat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Kind = "Expense",
                            Name = "Investment",
                            Slug = "investment"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Kind = "Expense",
                            Name = "MF",
                            ParentCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Slug = "mutual-fund"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Kind = "Expense",
                            Name = "PPF",
                            ParentCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Slug = "ppf"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Kind = "Expense",
                            Name = "FD",
                            ParentCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Slug = "fixed-deposit"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Kind = "Expense",
                            Name = "Bonds",
                            ParentCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Slug = "bonds"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Kind = "Expense",
                            Name = "Stocks",
                            ParentCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Slug = "stocks"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Kind = "Expense",
                            Name = "Gold",
                            ParentCategoryId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Slug = "gold"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Kind = "Expense",
                            Name = "Food",
                            Slug = "food"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Kind = "Expense",
                            Name = "Grocery",
                            Slug = "grocery"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Kind = "Expense",
                            Name = "Rent",
                            Slug = "rent"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Kind = "Income",
                            Name = "Salary",
                            Slug = "salary"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Kind = "Expense",
                            Name = "Travel",
                            Slug = "travel"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.DocumentImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_document_imports_content_hash");

                    b.ToTable("document_imports", null, t =>
                        {
                            t.HasCheckConstraint("ck_document_imports_content_hash_length", "length(content_hash) = 64");
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.ExpenseTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("account_label");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance_after");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("direction");

                    b.Property<Guid?>("DocumentImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_import_id");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_reference");

                    b.Property<int?>("ImportPosition")
                        .HasColumnType("integer")
                        .HasColumnName("import_position");

                    b.Property<string>("LineExtractionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("line_extraction_status");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("text")
                        .HasColumnName("receipt_url");

                    b.Property<string>("SourceFormat")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_format");

                    b.Property<int?>("SourceSequence")
                        .HasColumnType("integer")
                        .HasColumnName("source_sequence");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("DocumentImportId")
                        .HasDatabaseName("ix_transactions_document_import_id");

                    b.HasIndex("ExternalReference")
                        .HasDatabaseName("ix_transactions_external_reference");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("ix_transactions_transaction_date");

                    b.HasIndex("DocumentImportId", "ImportPosition")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_import_position");

                    b.HasIndex("TransactionDate", "Amount", "Direction", "ExternalReference")
                        .HasDatabaseName("ix_transactions_duplicate_detection");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transactions_amount_non_negative", "amount >= 0");

                            t.HasCheckConstraint("ck_transactions_import_position_non_negative", "import_position IS NULL OR import_position >= 0");

                            t.HasCheckConstraint("ck_transactions_provenance", "(origin = 'Manual' AND document_import_id IS NULL AND import_position IS NULL AND source_format IS NULL) OR (origin = 'Imported' AND document_import_id IS NOT NULL AND import_position IS NOT NULL AND source_format IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.TransactionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("line_type");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<decimal?>("UnitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_amount");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_transaction_lines_transaction_position");

                    b.ToTable("transaction_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_transaction_lines_amount_non_negative", "amount >= 0");

                            t.HasCheckConstraint("ck_transaction_lines_position_non_negative", "position >= 0");

                            t.HasCheckConstraint("ck_transaction_lines_quantity_non_negative", "quantity IS NULL OR quantity >= 0");

                            t.HasCheckConstraint("ck_transaction_lines_unit_amount_non_negative", "unit_amount IS NULL OR unit_amount >= 0");
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.Category", b =>
                {
                    b.HasOne("ExpenseTracker.Models.Persistence.Category", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.ExpenseTransaction", b =>
                {
                    b.HasOne("ExpenseTracker.Models.Persistence.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExpenseTracker.Models.Persistence.DocumentImport", "DocumentImport")
                        .WithMany("Transactions")
                        .HasForeignKey("DocumentImportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("DocumentImport");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.TransactionLine", b =>
                {
                    b.HasOne("ExpenseTracker.Models.Persistence.ExpenseTransaction", "Transaction")
                        .WithMany("Lines")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.DocumentImport", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseTracker.Models.Persistence.ExpenseTransaction", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
