import type { SpendingRow } from '../api/types'
export type FlowClass = 'income' | 'expense'
export const classify = (row: SpendingRow): FlowClass => row.categoryKind === 'Income' ? 'income' : row.categoryKind === 'Expense' ? 'expense' : row.direction === 'Credit' ? 'income' : 'expense'
export const signedTotal = (row: SpendingRow) => { const natural = row.direction === 'Credit' ? 'income' : 'expense'; return Math.round(row.total * 100) * (classify(row) === natural ? 1 : -1) / 100 }
export interface PeriodFlow { periodStart: string; income: number; expense: number }
export interface SeriesDescriptor { key: string; name: string; colorToken: string }
export interface CategorySlice extends SeriesDescriptor { total: number }
const sorted = (rows: SpendingRow[]) => [...rows].sort((a, b) => a.periodStart.localeCompare(b.periodStart))
const descriptor = (key: string, name: string, rank: number): SeriesDescriptor => ({ key, name, colorToken: key === 'other' || key === 'uncategorized' ? '--chart-neutral' : `--chart-${(rank % 8) + 1}` })
export const incomeExpenseByPeriod = (rows: SpendingRow[]): PeriodFlow[] => { const map = new Map<string, PeriodFlow>(); for (const row of sorted(rows)) { const item = map.get(row.periodStart) ?? { periodStart: row.periodStart, income: 0, expense: 0 }; const value = signedTotal(row); item[classify(row)] += value; map.set(row.periodStart, item) } return [...map.values()] }
export const expenseByCategory = (rows: SpendingRow[]) => { const totals = new Map<string, { name: string; cents: number }>(); for (const row of rows) if (classify(row) === 'expense') { const key = row.categoryId ?? 'uncategorized'; const old = totals.get(key) ?? { name: row.categoryName ?? 'Uncategorized', cents: 0 }; old.cents += Math.round(signedTotal(row) * 100); totals.set(key, old) } const ranked = [...totals.entries()].sort((a, b) => Math.abs(b[1].cents) - Math.abs(a[1].cents)); const slices = ranked.filter(([, value]) => value.cents > 0).map(([key, value], rank) => ({ ...descriptor(key, value.name, rank), total: value.cents / 100 })); const refundOnly = ranked.filter(([, value]) => value.cents < 0).map(([key, value], rank) => ({ ...descriptor(key, value.name, rank), total: value.cents / 100 })); return { slices, refundOnly } }
export interface StackedPeriod { periodStart: string; [key: string]: string | number }
export const expenseStacks = (rows: SpendingRow[], topN: number) => { const categoryTotals = new Map<string, { name: string; cents: number }>(); for (const row of rows) if (classify(row) === 'expense') { const key = row.categoryId ?? 'uncategorized'; const old = categoryTotals.get(key) ?? { name: row.categoryName ?? 'Uncategorized', cents: 0 }; old.cents += Math.round(signedTotal(row) * 100); categoryTotals.set(key, old) } const ranked = [...categoryTotals.entries()].sort((a, b) => Math.abs(b[1].cents) - Math.abs(a[1].cents)); const kept = new Set(ranked.filter(([key], index) => key === 'uncategorized' || index < topN).map(([key]) => key)); const periods = new Map<string, StackedPeriod>(); for (const row of sorted(rows)) if (classify(row) === 'expense') { const key = row.categoryId ?? 'uncategorized'; const seriesKey = kept.has(key) ? key : 'other'; const item = periods.get(row.periodStart) ?? { periodStart: row.periodStart }; item[seriesKey] = Number(item[seriesKey] ?? 0) + signedTotal(row); periods.set(row.periodStart, item) } const names = new Map(ranked.map(([key, value]) => [key, value.name])); const series = [...new Set([...ranked.filter(([key], index) => kept.has(key) && index < topN).map(([key]) => key), ...(ranked.some(([key]) => !kept.has(key)) ? ['other'] : []), ...(kept.has('uncategorized') ? ['uncategorized'] : [])])].map((key, index) => descriptor(key, key === 'other' ? 'Other' : names.get(key) ?? 'Uncategorized', index)); return { periods: [...periods.values()], series } }
